users:
  user:
    username: "user"
    password: "user"
    email: "user@todo.fr"
    role: "ROLE_USER"
  admin:
    username: "admin"
    password: "admin"
    email: "admin@todo.fr"
    role: "ROLE_ADMIN"
  anonym:
    username: "anonym"
    password: "anonym"
    email: "anonym@todo.fr"
    role: "ROLE_USER"